import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface FeedLayoutProps {
  children: React.ReactNode
}

export default function FeedLayout({ children }: FeedLayoutProps) {
  return <main>{children}</main>
}
